language: java
jdk: oraclejdk8

install: true
script: mvn install

after_success:
- ls -l
- cp -r /home/travis/build/garashis/Spring/target/demo-0.0.1-SNAPSHOT.jar target
- git add .
- git config --global user.email "ashishg.garg@gmail.com"
- git config --global user.name "Ashish Garg"
- git commit -m "Travis Adding Build File"
- git push -fq origin master
- echo -e "Done with magic\n"